//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTurno
    {
        public int Id_DetTur { get; set; }
        public int Id_Tur { get; set; }
        public int Id_TS { get; set; }
        public int Id_Pers { get; set; }
        public string Estado { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
