//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaxPromocion
    {
        public int Id_DxP { get; set; }
        public int Id_Dia { get; set; }
        public int Id_Prom { get; set; }
        public Nullable<System.DateTime> Duracion { get; set; }
        public string Estado { get; set; }
    
        public virtual Dia Dia { get; set; }
        public virtual Promocion Promocion { get; set; }
    }
}
