//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labor
    {
        public int IdLabor { get; set; }
        public int Id_TipS { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Detalle { get; set; }
    
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
